# Generated by Django 5.2.17 on 2026-09-14 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('USER_REGISTERED', 'User registered'), ('LOGIN_SUCCESS', 'Login successful'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'User logged out'), ('PASSWORD_CHANGED', 'Password changed'), ('PASSWORD_RESET_REQUESTED', 'Password reset requested'), ('PASSWORD_RESET_COMPLETED', 'Password reset completed'), ('EMAIL_VERIFIED', 'Email verified'), ('INVITATION_SENT', 'Invitation sent'), ('INVITATION_ACCEPTED', 'Invitation accepted'), ('ACCOUNT_STATUS_CHANGED', 'Account status changed'), ('SECURITY_ALERT', 'Security alert')], db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_created', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='audit_audit_event_t_124af2_idx')],
            },
        ),
    ]
