# Generated by Django 5.2.17 on 2026-09-28 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wills', '0002_rename_wills_will_owner__5bc9e9_idx_wills_will_owner_i_744445_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='will',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wills', to=settings.AUTH_USER_MODEL),
        ),
    ]
